Models/Member.cs
using System.ComponentModel.DataAnnotations;
#pragma warning disable CS8618
namespace Giftr.Models;
public class Member
{
    [Key]
    public int MemberId {get;set;}
    public int UserId {get;set;}
    [Display(Name = "Select Gift Exchange")]
    public int GiftExchangeId {get;set;}
    public User? User {get;set;}
    public GiftExchange? GiftExchange {get;set;}
    public DateTime CreatedAt { get; set; } = DateTime.Now;
	public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

Controllers/MemberController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters; //SessionCheck
using Microsoft.EntityFrameworkCore; // .Include(), and other methods
using Giftr.Models;

namespace Giftr.Controllers;

public class MemberController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private MyContext _context;
    
    public MemberController(ILogger<HomeController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

//******************************JOIN GIFT EXCHANGE FORM***********************************************
    [SessionCheck]
    [HttpGet("members/new")]
    public IActionResult MemberForm()
    {
        ViewBag.AllGiftExchanges = _context.GiftExchanges.OrderBy(c=>c.ExchangeDate).ToList();
        return View();
    }

//******************************CREATE MEMBER***********************************************
    [SessionCheck]
    [HttpPost("members/create")]
    public IActionResult CreateMember(ValidateGroupCode newMember)
    {
        if (ModelState.IsValid)
        {
            //find gift exchange that was selected in form
            GiftExchange? giftExchangeInDb = _context.GiftExchanges.FirstOrDefault(c=>c.GiftExchangeId == newMember.VGiftExchangeId);

            //create member object with session-UserId and giftExchangeId from form
            Member MemberToAdd = new Member()
            {
            UserId = (int)HttpContext.Session.GetInt32("UserId"),
            GiftExchangeId = newMember.VGiftExchangeId
            };

            //verify that MemberToAdd is unique, if not render error msg and View to form 
            if (_context.Members.Any(m=>m.GiftExchangeId == MemberToAdd.GiftExchangeId && m.UserId == MemberToAdd.UserId))
            {
                ModelState.AddModelError("VGroupCode", "You are already a member of this Gift Exchange!");
                ViewBag.AllGiftExchanges = _context.GiftExchanges.OrderBy(c=>c.ExchangeDate).ToList();
                return View("MemberForm");
            }

            //verify that the groupCode is correct. If so, add member to DB
            if(newMember.VGroupCode == giftExchangeInDb.GroupCode)
            {
                _context.Members.Add(MemberToAdd);
                _context.SaveChanges();
                return RedirectToAction("Dashboard", "GiftExchange");
            }
        }
        //Return to the memberform with viewbag of all GE's
        ViewBag.AllGiftExchanges = _context.GiftExchanges.OrderBy(c=>c.ExchangeDate).ToList();
        return View("MemberForm");
    }
}

Views/Member/MemberForm.cshtml
@{
    ViewData["Title"] = "Join a Gift Exchange";
}
@model ValidateGroupCode
<div>
    @await Html.PartialAsync("_Navbar")

    <h3 class="header">Join a Gift Exchange</h3>

    <div class="text-center">
        <a type="button" class="smBtn" asp-action="Dashboard" asp-controller="GiftExchange"><small>Return to Dashboard</small></a>
    </div>

    <hr class="line w-25 m-auto">

    <form class="m-3" asp-action="CreateMember" asp-controller="Member" method="post">

        <div class="formItem">
            <label asp-for="VGiftExchangeId"></label>
            <select asp-for="VGiftExchangeId" class="form-control">

                <option disabled selected value="">Select a Gift Exchange</option>

                @foreach(GiftExchange g in ViewBag.AllGiftExchanges)
                {
                <option value=@g.GiftExchangeId>@g.Name</option>
                }
            </select>
            <span asp-validation-for="VGiftExchangeId" class="text-danger"></span>
        </div>

        <div class="formItem">
            <label asp-for="VGroupCode"></label>
            <input asp-for="VGroupCode" class="form-control">
            <span asp-validation-for="VGroupCode" class="text-danger"></span>
        </div>
        <div class="text-center">
            <button class="lgBtn btn" type="submit">Join Gift Exchange!</button>
        </div>

    </form>

</div>