Models/GiftExchange.cs
using System.ComponentModel.DataAnnotations;
#pragma warning disable CS8618
namespace Giftr.Models;
public class GiftExchange
{
    [Key]
    public int GiftExchangeId {get;set;}

    [Required]
    [MinLength(2)]
    public string Name {get;set;}
    [Required]
    [DataType(DataType.Password)]
    [MinLength(3, ErrorMessage = "GroupCode must be at least 3 characters long")]
    public string GroupCode {get;set;}
    [Required]
    [Range(0,10000)]
    public int Budget {get;set;}
    [Required]
    [FutureDate]
    public DateTime ExchangeDate {get;set;}
    [Required]
    public string Details {get;set;}
    [Required]
    public int UserId {get;set;}
	public User? Admin {get;set;}
    public List<Member> MemberList {get;set;} = new List<Member>();
    public DateTime CreatedAt { get; set; } = DateTime.Now;
	public DateTime UpdatedAt { get; set; } = DateTime.Now;
}

public class FutureDateAttribute : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        if(value == null)
        {
            return new ValidationResult("Date is required!");
        }

		DateTime WedDate = Convert.ToDateTime(value);
		if(DateTime.Compare(WedDate, DateTime.Now) <= 0)
        {
            return new ValidationResult("Project date must be in the future!");
        } else {
            return ValidationResult.Success;
        }
    }
}

Controllers/GiftExchangeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters; //SessionCheck
using Microsoft.EntityFrameworkCore; // .Include(), and other methods
using Giftr.Models;

namespace Giftr.Controllers;

public class GiftExchangeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private MyContext _context;
    
    public GiftExchangeController(ILogger<HomeController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

//******************************DASHBOARD***********************************************
    [SessionCheck]
    [HttpGet("giftexchange/dashboard")]
    public IActionResult Dashboard()
    {
        MyViewModel MyModels = new MyViewModel
        {
            AllGiftExchanges = _context.GiftExchanges.Include(ge=>ge.MemberList)
                                                    .ThenInclude(m=>m.User)
                                                    .OrderBy(ge=>ge.ExchangeDate)
                                                    .ToList()
        };

        return View(MyModels);
    }

//******************************GIFT EXCHANGE FORM***********************************************
    [SessionCheck]
    [HttpGet("giftexchanges/new")]
    public IActionResult GiftExchangeForm()
    {
        return View();
    }

//******************************CREATE GIFT EXCHANGE***********************************************
    [SessionCheck]
    [HttpPost("giftexchanges/create")]
    public IActionResult CreateGiftExchange(GiftExchange newGiftExchange)
    {
        if (ModelState.IsValid)
        {
            //add new GE to DB
            _context.GiftExchanges.Add(newGiftExchange);

            //save the new gift exchange
            _context.SaveChanges();

            //make admin a member of new GE
            Member adminMember = new Member()
            {
                UserId = (int)HttpContext.Session.GetInt32("UserId"),
                GiftExchangeId = newGiftExchange.GiftExchangeId
            };
            _context.Members.Add(adminMember);
            
            //save and return to dashboard
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        return View("GiftExchangeForm");
    }

//******************************DISPLAY GIFT EXCHANGE and MEMBERS***********************************************
    [SessionCheck]
    [HttpGet("giftexchanges/{GiftExchangeId}")]
    public IActionResult OneGiftExchange(int GiftExchangeId)
    {
        MyViewModel MyModels = new MyViewModel
        {
            GiftExchange = _context.GiftExchanges.Include(ge=>ge.MemberList)
                                        .ThenInclude(m=>m.User)
                                        .ThenInclude(u=>u.ItemList)
                                        .FirstOrDefault(ge=>ge.GiftExchangeId == GiftExchangeId)
        };

        return View(MyModels);
    }

    //******************************EDIT GIFT EXCHANGE***********************************************
    [SessionCheck]
    [HttpGet("giftexchanges/{GiftExchangeId}/edit")]
    public IActionResult EditGiftExchange(int GiftExchangeId)
    {
        GiftExchange? GEInDb = _context.GiftExchanges.FirstOrDefault(ge=>ge.GiftExchangeId == GiftExchangeId);
        return View(GEInDb);
    }

    //******************************UPDATE GIFT EXCHANGE***********************************************
    [SessionCheck]
    [HttpPost("giftexchanges/{GiftExchangeId}/update")]
    public IActionResult UpdateGiftExchange(GiftExchange GEToUpdate, int GiftExchangeId)
    {

        //find GE that we will update
        GiftExchange? OldGE = _context.GiftExchanges.FirstOrDefault(ge=>ge.GiftExchangeId == GiftExchangeId);

        System.Console.WriteLine("*******************in update page");
        if (ModelState.IsValid)
        {
            System.Console.WriteLine("*******************in IF condition ");

            //set oldGE to new values
            OldGE.Name = GEToUpdate.Name;
            OldGE.GroupCode = GEToUpdate.GroupCode;
            OldGE.Budget = GEToUpdate.Budget;
            OldGE.ExchangeDate = GEToUpdate.ExchangeDate;
            OldGE.Details = GEToUpdate.Details;
            OldGE.UpdatedAt = DateTime.Now;
            _context.SaveChanges();

            return RedirectToAction("OneGiftExchange", new {GiftExchangeId});
        } else {
            return View("EditGiftExchange", OldGE);
        }
    }
}

Controllers/ItemController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters; //SessionCheck
using Microsoft.AspNetCore.Identity; //Password Hasher
using Microsoft.EntityFrameworkCore; // .Include(), and other methods
using Giftr.Models;

namespace Giftr.Controllers;

public class ItemController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private MyContext _context;

    public ItemController(ILogger<HomeController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

//******************************SHOW A WISHLIST***********************************************
    [SessionCheck]
    [HttpGet("items/{UserId}")]
    public IActionResult OneWishList(int UserId)
    {
        System.Console.WriteLine("*****************" + UserId);
        MyViewModel MyModels = new MyViewModel
        {
            User = _context.Users.Include(u=>u.ItemList)
                                .Include(u=>u.Memberships)
                                .FirstOrDefault(u=>u.UserId == UserId)
        };
    return View(MyModels);
    }

//******************************ADD ITEM FORM***********************************************
    [SessionCheck]
    [HttpGet("items/new")]
    public IActionResult AddItem()
    {
        MyViewModel MyModels = new MyViewModel
        {
            User = _context.Users.Include(u=>u.ItemList)
                                .FirstOrDefault(u=>u.UserId == HttpContext.Session.GetInt32("UserId"))
        };
    return View(MyModels);
    }

//******************************CREATE ITEM***********************************************
    [SessionCheck]
    [HttpPost("items/create")]
    public IActionResult CreateItem(Item newItem)
    {
        if (ModelState.IsValid)
        {
            _context.Items.Add(newItem);
            _context.SaveChanges();
            return RedirectToAction("OneWishList", new {newItem.UserId});
        } else 
        {
        MyViewModel MyModels = new MyViewModel
        {
            User = _context.Users.Include(u=>u.ItemList)
                                .FirstOrDefault(u=>u.UserId == HttpContext.Session.GetInt32("UserId"))
        };
        return View("AddItem", MyModels);
        }
    }

//******************************EDIT ITEM FORM***********************************************
    [SessionCheck]
    [HttpGet("items/{ItemId}/edit")]
    public IActionResult EditItem(int ItemId)
    {
        MyViewModel MyModels = new MyViewModel
        {
            Item = _context.Items.FirstOrDefault(i=>i.ItemId == ItemId),
            User = _context.Users.Include(u=>u.ItemList)
                                .FirstOrDefault(u=>u.UserId == HttpContext.Session.GetInt32("UserId"))
        };
        return View(MyModels);
    }

//******************************UPDATE ITEM***********************************************
    [SessionCheck]
    [HttpPost("items/{ItemId}/update")]
    public IActionResult UpdateItem(Item ItemToUpdate, int ItemId)
    {
        System.Console.WriteLine("before modelstate");
        if (ModelState.IsValid)
        {
            System.Console.WriteLine("after modelstate");
            Item? OldItem = _context.Items.FirstOrDefault(i=>i.ItemId == ItemId);
            
            OldItem.Name = ItemToUpdate.Name;
            OldItem.Description = ItemToUpdate.Description;
            OldItem.Image = ItemToUpdate.Image;
            OldItem.UpdatedAt = DateTime.Now;

            _context.SaveChanges();
            return RedirectToAction("OneWishList", new {OldItem.UserId});
        }
        return View("EditItem", ItemId);
    }
    //******************************DESTROY ITEM***********************************************
    [SessionCheck]
    [HttpPost("items/{ItemId}/destroy")]
    public IActionResult DestroyItem(int ItemId)
    {
        System.Console.WriteLine(ItemId);
        Item? ItemToDelete = _context.Items.SingleOrDefault(i=>i.ItemId == ItemId);

        _context.Items.Remove(ItemToDelete);
        _context.SaveChanges();
        return RedirectToAction("OneWishList", new {ItemToDelete.UserId});
    }
}

Views/GiftExchange/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
@model MyViewModel
<div>
    @await Html.PartialAsync("_Navbar")

    

    <div class="list">
        <h3 class="header">Your Gift Exchanges</h3> 
        <div class="m-3">
            <small>Here are all the gift exchanges you are a member of! </small>
            <hr class="line">
        </div>

        <div class="d-flex flex-column m-4">
        @foreach(GiftExchange g in Model.AllGiftExchanges)
        {
            if(g.MemberList.Any(m=>m.UserId == Context.Session.GetInt32("UserId")))
            {
            <a class="btn listItem" asp-action="OneGiftExchange" asp-controller="GiftExchange" asp-route-GiftExchangeId="@g.GiftExchangeId" method="get">
                <strong>@g.Name</strong> - @g.MemberList.Count Members
            </a>
            }
        }
        </div>
    </div>

    <div class="d-flex justify-content-center m-4">
        <div class="d-flex flex-column justify-content-center m-4 ">
            <small>Want to Join an Already Existing Gift Exchange?</small>
            <a class="p-2 btn text-center fs-5 lgBtn" href="/members/new">Join a Gift Exchange</a>
        </div>
        <div class="d-flex flex-column justify-content-center m-4 ">
            <small>Want to Create a New Gift Exchange?</small>
            <a class="p-2 btn text-center fs-5 lgBtn" href="/giftexchanges/new">Create a Gift Exchange</a>
        </div>
    </div>

</div>

Views/GiftExchange/EditGiftExchange.cshtml
@{
    ViewData["Title"] = "Edit Gift Exchange";
}
@model GiftExchange
<div>
    @await Html.PartialAsync("_Navbar")

    <h3 class="header">Edit this Gift Exchange</h3>
    
    <div class="text-center">
        <a type="button" class="smBtn" asp-action="OneGiftExchange" asp-controller="GiftExchange" asp-route-GiftExchangeId=@Model.GiftExchangeId><small>Return</small></a>
    </div>

    <hr class="line w-25 m-auto">

    <form class="m-3" asp-action="UpdateGiftExchange" asp-controller="GiftExchange" asp-route-GiftExchangeId=@Model.GiftExchangeId method="post">

        <div class="formItem">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
            
        <div class="formItem">
            <label asp-for="Budget"></label>
            <input asp-for="Budget" class="form-control">
            <span asp-validation-for="Budget" class="text-danger"></span>
        </div>
        
        <div class="formItem">
            <label asp-for="ExchangeDate"></label>
            <input asp-for="ExchangeDate" class="form-control">
            <span asp-validation-for="ExchangeDate" class="text-danger"></span>
        </div>

        <div class="formItem">
            <label asp-for="Details"></label>
            <textarea asp-for="Details" class="form-control"></textarea>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>

        <input type="hidden" asp-for="UserId" value=@Context.Session.GetInt32("UserId") >
        <input type="hidden" asp-for="GroupCode" value=@Model.GroupCode>

        <div class="text-center">
            <button class="lgBtn btn" type="submit">Update</button>
        </div>
        
    </form>
</div>

Views/GiftExchange/GiftExchangeForm.cshtml
@{
    ViewData["Title"] = "Create Gift Exchange";
}
@model GiftExchange
<div>
    @await Html.PartialAsync("_Navbar")

    <h3 class="header">Create a new Gift Exchange</h3>

    <div class="text-center">
        <a type="button" class="smBtn" asp-action="Dashboard" asp-controller="GiftExchange"><small>Return to Dashboard</small></a>
    </div>

    <hr class="line w-25 m-auto">

    <form class="m-3" asp-action="CreateGiftExchange" asp-controller="GiftExchange" method="post">

        <div class="formItem">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="formItem">
            <label asp-for="GroupCode"></label>
            <small>*For others to join your gift exchange, they will need this GroupCode*</small>
            <input asp-for="GroupCode" class="form-control">
            <span asp-validation-for="GroupCode" class="text-danger"></span>
        </div>

        <div class="formItem">
            <label asp-for="Budget"></label>
            <input asp-for="Budget" class="form-control">
            <span asp-validation-for="Budget" class="text-danger"></span>
        </div>
        
        <div class="formItem">
            <label asp-for="ExchangeDate"></label>
            <input asp-for="ExchangeDate" class="form-control">
            <span asp-validation-for="ExchangeDate" class="text-danger"></span>
        </div>

        <div class="formItem">
            <label asp-for="Details"></label>
            <textarea asp-for="Details" class="form-control"></textarea>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>

        <input type="hidden" asp-for="UserId" value=@Context.Session.GetInt32("UserId") >

        <div class="text-center">
            <button class="lgBtn btn" type="submit">Create Gift Exchange</button>
        </div>
        
    </form>
</div>

Views/GiftExchange/OneGiftExchange.cshtml
@{
    ViewData["Title"] = "Gift Exchange Details";
}
@model MyViewModel
<div>
    @await Html.PartialAsync("_Navbar")
    
    <div class="text-center">
        <h3 class="header">The <span class="glow">@Model.GiftExchange.Name</span> Gift Exchange</h3 class="header">
        @if(Model.GiftExchange.UserId == Context.Session.GetInt32("UserId"))
        {
        <a class="smBtn" href="/GiftExchanges/@Model.GiftExchange.GiftExchangeId/edit">
            Edit Gift Exchange
        </a>
        }
        <hr class="line w-50 m-auto">
    </div>
    

    <div class="d-flex justify-content-center m-5">
        <div class="list mx-5">
            <h3>Members</h3>
            @foreach (Member m in Model.GiftExchange.MemberList)
            {
                <a class="btn listItem" asp-action="OneWishlist" asp-controller="Item" asp-route-UserId=@m.User.UserId>
                    <strong>@m.User.Username</strong> - @m.User.ItemList.Count() Item(s)
                </a>
            }
        </div>

        <div class="vLine"></div>

        <div class="text mx-5">
            <div class="details">
                <p class="dheader">Details</p class="dheader">
                <p class="">@Model.GiftExchange.Details</p>
            </div>
            
            <div class="details">
                <p class="dheader">Budget</p class="dheader">
                <p>$@Model.GiftExchange.Budget</p>
            </div>

            <div class="details">
                <p class="dheader">Exchange Date</p class="dheader">
                <p>@Model.GiftExchange.ExchangeDate.ToString("MMMM dd, yyyy")</p>
            </div>        
        </div>
    </div>

</div>